### ISSUE TITLE
Array of templates and Array of random values with random amount

### ISSUE THREAD

**Issue by jimkoen** [up9inc/mockintosh#159]
Hello!

I'm sorry if this has been answered before, but is it possible to generate arrays from templates?

I.e. I have a template looking like this:
`device.json.j2`:
```json
'{ 
"name" : "{{ fake.last_name() }}",
"address" : "{{ fake.ipv4() }}",
"port" : "{{ random.int 1 65536 }}",
}'
```

And inside a response I'd like to retrieve an array of devices with variable length. I.e. I'd like to mock when an endpoint returns a collection of devices.

My attempt so far looks like this (note the multiple template listings, as I've been unable to figure out how to tell the array to generate X amount of templated devices):

`mockconf.yaml`
```yaml
- path: /pnds/{{ pndUuid }}/devices
    method: GET
    response:
    - status: 200
      content-type: application/json
      body:
        {{ array '@templates/list_entity.json.j2' '@templates/list_entity.json.j2' '@templates/list_entity.json.j2' }}
```

My intention is it, to have an endpoint generate a bunch of these devices, to mock returning collections of devices from the endpoint.
