### ISSUE TITLE
`fromjson` method in templates

### ISSUE THREAD

**Issue by chason-choate** [up9inc/mockintosh#164]
We have a use-case where we are using the reactive consumer and want to alter the JSON emitted from the producer. 

Therefore i'd propose adding a `fromjson` method to mirror the `tojson` method. This gives templates more flexibility in how it deals with data.

**Comment by undera** [comment]
Can you elaborate? Maybe add example with config how would it look?

**Comment by chason-choate** [comment]
Sure thing, here is how we are using it:

Our reactive consumer config:

```
  - name: Kafka Actors
    type: kafka
    address: kafka:9092
    actors:
      - name: reactive
        consume:
          queue: input-topic
        produce:
          queue: output-topic
          value: '@output-response.json.hbs' 
```

And the `output-response.json.hbs` template:

NOTE: We've edited the `hbs/methods.py` file to add this `fromjson` method.

```
{{ tojson (jsonPath (fromjson consumed.value) '$.payload') }}
```
