### ISSUE TITLE
Multiple yaml config [suggestion]

### ISSUE THREAD

**Issue by sergeidyga** [up9inc/mockintosh#166]
In case of many services being mocked - it would be easier to keep configs for each service in separate file.
like this:
`example-service-1.yaml`
```yaml
- name: example-service-1
      port: 80
      endpoints:
        - path: ...
```
`example-service-2.yaml`
```yaml
- name: example-service-2
      port: 80
      endpoints:
        - path: ...
```
