### ISSUE TITLE
variables from schema cannot be used in producer

### ISSUE THREAD

**Issue by Jozef63** [up9inc/mockintosh#174]
Hello, I am using reactive producer for kafka mock actor as described here in [documentation](https://mockintosh.io/Async.html)

The variables from consumer are not present in producer

here is a dummy code for actors configuration that I am using : 

```
      - name: dummy-mock
        consume:
          queue: REQUEST
          capture: 10
          schema: "@value/Request.json"
        produce:
          queue: RESPONSE
          key: "can reference as {{consumed.value}}"
          value: "@value/Response.json"
```

here is Request.json: 
```
{
  "someId": "{{someId}}",
  "code": "{{code}}"
}
```
here is Response.json:
```
{
  "someId": "{{someId}}",
  "code": "{{code}}",
  "someOtherField": "someValue"
}
```

after producing a message like: 
```
{
  "someId": "someValue",
  "code": "someValue"
}
```

the consumer receives message, producer produces a message too but I get following warning:

`[2022-08-18 12:41:47,241 root WARNING] Handlebars: Could not find variable 'someId'`

and the produced message is without filled values : 
```
{
  "someId": "{{someId}}",
  "code": "{{code}}",
  "someOtherField": "someValue"
}
```
