### ISSUE TITLE
configuring kafka address using environment variable doesn't work

### ISSUE THREAD

**Issue by oxeye-schmil** [up9inc/mockintosh#183]
I used the following configuration for kafka

```
management:
  port: 8000

services:
  - name: Kafka Mock Actors
    type: kafka
    address: "{{env 'KAFKA'}}"
    actors:
      - name: span
        produce:
          create: true
          queue: jaeger-spans
          value: "@/span1.json"
```

But when I triggered the produce I got the following error in logs
```
%3|1671090820.157|FAIL|rdkafka#producer-1| [thrd:{{env 'KAFKA'}}:9092/bootstrap]: {{env 'KAFKA'}}:9092/bootstrap: Failed to resolve '{{env 'KAFKA'}}:9092': Name or service not known (after 0ms in state CONNECT, 28 identical error(s) suppressed)
```
