### ISSUE TITLE
Modifying YAML key-value pair order is failed to apply

### ISSUE THREAD

**Issue by QAInsights** [up9inc/mockintosh#74]
When I modify the key-value pair order in the YAML in Configuration page, it is not applying the YAML as it is losing the YAML format in the request payload.

Initial YAML
```
services:
- name: Search Service
  performanceProfile: loadprofile
  hostname: localhost
  port: 8001
  endpoints:
  - path: /
```

Modified YAML in the Configuration page

```
services:
- name: Search Service
  port: 8001
  performanceProfile: loadprofile
  hostname: localhost
  endpoints:
  - path: /
```

After hitting `Applying Changes`. Here is the output:
![image](https://user-images.githubusercontent.com/2826376/111043917-4f1b6900-843d-11eb-980f-016fdfc736c2.png)

Request Payload
![image](https://user-images.githubusercontent.com/2826376/111043930-6b1f0a80-843d-11eb-962c-48d049e9abdf.png)
